apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: nginx
  newName: registry.drupal-tutorial.svc.cluster.local:5000/project1/nginx
  newTag: 0.0.1
- name: php
  newName: registry.drupal-tutorial.svc.cluster.local:5000/project1/php
  newTag: 0.0.1

resources:
- kubernetes/configmap.yaml
- kubernetes/cronjob.yaml
- kubernetes/deployment.yaml
- kubernetes/hpa.yaml
- kubernetes/pvc.yaml
- kubernetes/service.yaml

commonLabels:
  app.kubernetes.io/component: application
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: project1
  app.kubernetes.io/part-of: drupal
