apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-public
spec:
  accessModes:
    - ReadWriteOnce
  # This will change based on infrastructure.
  #   - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  # This will need to be set based on infrastructure.
  # storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-private
spec:
  accessModes:
    - ReadWriteOnce
  # This will change based on infrastructure.
  #   - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  # This will need to be set based on infrastructure.
  # storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-temporary
spec:
  accessModes:
    - ReadWriteOnce
  # This will change based on infrastructure.
  #   - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  # This will need to be set based on infrastructure.
  # storageClassName: standard